version: '3'

services:
  gateway:
    build: ./images/gateway
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./images/gateway/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro

  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost/auth
      - KEYCLOAK_LOGLEVEL=ALL
      - PROXY_ADDRESS_FORWARDING=true
    command:
      - -b
      - 0.0.0.0
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=dir
      - -Dkeycloak.migration.dir=/migration
      - -Dkeycloak.migration.strategy=IGNORE_EXISTING
    volumes:
      - ./images/keycloak/migration:/migration:ro
      - ./mounts/keycloak:/opt/jboss/keycloak/standalone/data

  frontend:
    build:
      context: .
      dockerfile: apps/ct-frontend/docker.dev/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: apps/ct-backend/docker.dev/Dockerfile
    environment:
      - TYPEORM_URL=mysql://user:password@database:3306/application
      - TYPEORM_LOGGING=true
      - TYPEORM_SYNCHRONIZE=true
    ports:
      - 127.0.0.1:40001:40001
    volumes:
      - ./:/app
      - /app/node_modules

  database:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=application
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --sql-mode=
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./mounts/mysql:/var/lib/mysql
    restart: always

  storage:
    image: satantime/minio-server:RELEASE.2022-04-01T03-41-39Z
    environment:
      - MINIO_ACCESS_KEY=123
      - MINIO_SECRET_KEY=12345678
    ports:
      - 127.0.0.1:9000:9000
    volumes:
      - ./mounts/minio:/data
    restart: always

  smtp:
    image: rnwood/smtp4dev:3.1.3.2
    command:
      - --smtpport
      - '1025'
      - --db
      - /tmp/smtp/mails.db
      - --messagestokeep
      - '1000'
      - --sessionstokeep
      - '1000'
    volumes:
      - ./mounts/smtp:/tmp/smtp
    restart: always
